### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by ICEPrey** [M2G/react-plyr#10]
Is there a download feature? Also I fixed #9, it wasn't resizing because I had it placed in a div with className.

**Comment by M2G** [comment]
"Also I fixed #9, it wasn't resizing because I had it placed in a div with className." Nice !!!
"Is there a download feature?" for audio and video ?

**Comment by ICEPrey** [comment]
Sorry I didn't clarify, in the controls can there be a download button?

**Comment by ICEPrey** [comment]
Not sure about audio, but for video yes

**Comment by M2G** [comment]
Add this : 

`controls={[
          'play-large',
          'play',
          'progress',
          'current-time',
          'mute',
          'volume',
          'captions',
          'settings',
          'pip',
          'airplay',
          'download',
          'fullscreen',
          ]}`

**Comment by ICEPrey** [comment]
Oh ok thank you
