### ISSUE TITLE
Question: Local Storage 

### ISSUE THREAD

**Issue by Tsuksi** [M2G/react-plyr#11]
How can I save player's timestamp into local storage?

**Comment by M2G** [comment]
Hi, if you want to get **current time**, you can get it with **onTimeUpdate**.

```javascript
<ReactPlyr
  onTimeUpdate={(currentTime) => {
      localStorage.setItem('currentTime', currentTime);
       console.log('currentTime', currentTime);
  }}
 />
```
I remain at your disposal for any further information,

Matt

**Comment by Tsuksi** [comment]
Ah ok thank you very much
