### ISSUE TITLE
I cant build my project with react-plyr

### ISSUE THREAD

**Issue by yojona** [M2G/react-plyr#15]
Im getting:
![image](https://user-images.githubusercontent.com/13840865/127784341-ce416349-c843-4697-8179-83b020f2bbfa.png)

can you help? @M2G 

im running: `npm run build --production`

**Comment by M2G** [comment]
thank you for this feedback, I will investigate

**Comment by M2G** [comment]
Hi, I fixed the npm pkg 

`https://www.npmjs.com/package/@m2g/react-plyr/v/1.3.8`

I remain at your disposal for any further information.

Matt
