### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by ICEPrey** [M2G/react-plyr#6]
Can you add the "Preview Thumbnail Scrubbing" https://github.com/sampotts/plyr/blob/aa3378fd7303c42059728155719ff57952bb0fcc/src/js/plugins/preview-thumbnails.js

**Comment by M2G** [comment]
hello, yes i will add your request "Preview Thumbnail Scrubbing" to my next release (which contains quality control from HLS - Youtube like)

**Comment by ICEPrey** [comment]
Ah thank you so much

**Comment by M2G** [comment]
You can see, in App.tsx file, an example (on master), i add : 
`previewThumbnails={{
  enabled: true,
  src: ['https://cdn.plyr.io/static/demo/thumbs/100p.vtt', 'https://cdn.plyr.io/static/demo/thumbs/240p.vtt'],
}}` and it works. (just make a : git pull origin master and run project)

**Comment by ICEPrey** [comment]
> You can see, in App.tsx file, an example (on master), i add :
> `previewThumbnails={{ enabled: true, src: ['https://cdn.plyr.io/static/demo/thumbs/100p.vtt', 'https://cdn.plyr.io/static/demo/thumbs/240p.vtt'], }}` and it works. (just make a : git pull origin master and run project)

thank you!
