### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by ICEPrey** [M2G/react-plyr#7]
Hello I was wondering when are you going to update this npm? https://www.npmjs.com/package/@m2g/react-plyr

**Comment by M2G** [comment]
Hello,

I'll update the "pkg npm" this week, I'll keep you posted.

**Comment by ICEPrey** [comment]
> Hello,
> 
> I'll update the "pkg npm" this week, I'll keep you posted.

Thank you

**Comment by ICEPrey** [comment]
Ah rip the npm got removed

**Comment by M2G** [comment]
yes, I've lost access to my npm account, so it has been deleted, while waiting for me to redo a configuration to publish again, you can fork (if you want)

**Comment by ICEPrey** [comment]
Oh sorry, I thought you discontinued it because you stopped working on it. Also I never published anything to npm so I really don't know how this process works sorry!

**Comment by M2G** [comment]
i will try to redo a configuration and an account to be able to publish and I will come back to you :)
(I still maintain the project on github, but I wasn't updating on npm)

**Comment by ICEPrey** [comment]
> i will try to redo a configuration and an account to be able to publish and I will come back to you :)
> (I still maintain the project on github, but I wasn't updating on npm)

Any updates?

**Comment by M2G** [comment]
I haven't had much time, I'll try to push a config npm at the end of the week

**Comment by ICEPrey** [comment]
Oh ok, sorry to rush you

**Comment by M2G** [comment]
Oh no, there is no problem :)

**Comment by M2G** [comment]
Hi,

I made an npm configuration and I'm waiting to be able to publish again (I have an error message: "@m2g/react-plyr cannot be republished until 24 hours have passed.") so I have to wait 24h

**Comment by ICEPrey** [comment]
Oh ok thank you very much (should I close this issue then?)

**Comment by M2G** [comment]
it's published : https://www.npmjs.com/package/@m2g/react-plyr/v/1.2.4

**Comment by ICEPrey** [comment]
Ah thank you very much!
